# ===== simu =====
seed: 1

simulation:
  max_agents: 10000
  init_agents: 2048
  birth_pool_size: 64
  wall_effect: "none"

logging:
  wandb_log: false
  sampling_freq:
  sampling_size: 16
  ckpt_freq:
  wandb_project: "eedx_ciliated"


# ===== chemical types =====

ct-1:
  diffusion_rate: 5.0
  is_sparse: false
  emission_rate: 1.0

ct-2:
  diffusion_rate: 10.0
  is_sparse: false
  emission_rate: 1.0

# ===== food types =====

ft-1:
  growth_rate: 0.001
  dmin: 1
  dmax: 1
  chemical_signature: 1
  energy_concentration: 0.5
  spontaneous_grow_prob: 0.0001
  initial_density: 1.0


# ===== env =====

env:
  size: [512,512]
  chemicals_detection_threshold: 0.001
  walls_density: 0.0

# ===== agents =====

agents:

  body_resolution: 16
  init_energy: 1.5
  max_energy: 20.0
  basal_energy_loss: 0.0
  size_energy_cost: 0.02
  reproduction_energy_cost: 2.0
  time_above_threshold_to_reproduce: 70
  time_below_threshold_to_die: 50
  min_body_size: 1.0
  max_body_size: 15.0
  max_age: 500

  motor:
    which: "ciliated"
    border_size: 0.2
    thrust_gain: 1.0
    max_beat: 1.0
    max_velocity: 8.0
    max_angular_speed: 0.78
    motor_energy_cost: 0.05
    dt: 1.0

  sensory:
    body_resolution: 6
    which: "spatially_embedded"
    sensor_expression_threshold: 0.1

  nn:
    which: "neuronca_ctrnn"
    size: 16
    synapse_channels: 8
    extra_channels: 16
    perception_channels: 3
    dev_steps: 50
    nb_wiring_rules: 4
    update_layers: 2

  mutation:
    which: "generalized"
    sigma: 0.03
    p_mut: 1.0
    sigma_size: 0.1
