seed: 1
simulation:
  max_agents: 10000
  init_agents: 2048
  birth_pool_size: 64
  wall_effect: none
logging:
  wandb_log: true
  sampling_freq: 10000
  sampling_size: 32
  ckpt_freq: null
  wandb_project: eedx
ct-1:
  diffusion_rate: 5.0
  is_sparse: false
  emission_rate: 1.0
ct-2:
  diffusion_rate: 5.0
  is_sparse: false
  emission_rate: 1.0
ft-1:
  growth_rate: 0.0
  dmin: 1
  dmax: 1
  chemical_signature: 1
  energy_concentration: 2
  spontaneous_grow_prob: 2e-4
  initial_density: 0.01
env:
  size:
  - 512
  - 512
  chemicals_detection_threshold: 1.0e-05
  walls_density: 0.0
agents:
  body_resolution: 8
  init_energy: 1.5
  max_energy: 15.0
  basal_energy_loss: 0.0
  size_energy_cost: 0.02
  reproduction_energy_cost: 1.0
  time_above_threshold_to_reproduce: 100
  time_below_threshold_to_die: 50
  min_body_size: 1.0
  max_body_size: 8.0
  max_age: 10000
  motor:
    which: ciliated_torque
    border_size: 0.3
    thrust_gain: 0.05
    max_beat: 0.1
    max_velocity: 0.5
    max_angular_speed: 0.785
    motor_energy_cost: 0.05
    size_speed_exponent: 0.5
    size_cost_exponent: 1.5
    dt: 1.0
  sensory:
    which: spatially_embedded
    body_resolution: 8
    sensor_expression_threshold: 0.1
  nn:
    which: rand_ctrnn
    body_morphogens: true
    init_neurons: 1
    max_neurons: 64
    sensory_genes: 7
    motor_genes: 1
    regulatory_genes: 8
    synaptic_genes: 4
    synaptic_proteins: 4
    body_morphogens: true
    wiring_model: mlp
    min_neuron_distance: 0.1
    wiring_model_kwargs: 
        final_activation: tanh
    dev_iters: 100
  mutation:
    which: generalized
    sigma: 0.03
    p_mut: 1.0
    sigma_size: 0.005
